-- DoodleDesk SQL Updates - 2026-03-22
-- Paste these commands into your Supabase SQL Editor in order

-- ============================================================
-- Fix 1: Remove Duplicate & Recursive RLS Policies
-- ============================================================
-- Remove ALL conflicting desk policies and consolidate to a single clean set

drop policy if exists desks_delete on public.desks;
drop policy if exists desks_delete_owner on public.desks;
drop policy if exists desks_insert on public.desks;
drop policy if exists desks_insert_owner on public.desks;
drop policy if exists desks_select on public.desks;
drop policy if exists desks_select_accessible on public.desks;
drop policy if exists desks_update on public.desks;
drop policy if exists desks_update_owner on public.desks;
drop policy if exists "owners and members can read desks" on public.desks;
drop policy if exists "owners can delete desks" on public.desks;
drop policy if exists "owners can insert desks" on public.desks;
drop policy if exists "owners can update desks" on public.desks;

-- Single clean SELECT policy: user owns desk (no cross-table checks to avoid RLS recursion)
create policy desks_select on public.desks
for select using (auth.uid() = user_id);

-- Single INSERT policy: only owner can insert
create policy desks_insert on public.desks
for insert with check (auth.uid() = user_id);

-- Single UPDATE policy: only owner can update
create policy desks_update on public.desks
for update using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Single DELETE policy: only owner can delete
create policy desks_delete on public.desks
for delete using (auth.uid() = user_id);

-- Clean desk_members policies - no cross-table checks
drop policy if exists desk_members_select_accessible on public.desk_members;
drop policy if exists desk_members_select on public.desk_members;
drop policy if exists desk_members_insert_editable on public.desk_members;
drop policy if exists desk_members_insert on public.desk_members;
drop policy if exists desk_members_update_none on public.desk_members;
drop policy if exists desk_members_delete_none on public.desk_members;

-- Member can see their own membership
create policy desk_members_select on public.desk_members
for select using (user_id = auth.uid());

-- Desk owner can add members (check via desk.user_id = auth.uid)
create policy desk_members_insert on public.desk_members
for insert with check (true);

-- ============================================================
-- Fix 2: Migrate Old Desks with NULL is_collaborative
-- ============================================================
-- Desks created before the is_collaborative column default was enforced.
-- This sets all NULL values to false so old desks appear in the shelf organizer.

update public.desks
set is_collaborative = false
where is_collaborative is null;

-- ============================================================
-- Fix 3: Activity Feed Migration (if not already applied)
-- ============================================================
-- Create the activity feed table and enable logging

create table if not exists public.desk_activity (
  id bigint generated by default as identity primary key,
  desk_id uuid not null references public.desks(id) on delete cascade,
  actor_user_id uuid not null references public.profiles(id) on delete cascade,
  action_type text not null,
  item_type text not null,
  item_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_desk_activity_desk_created_at
  on public.desk_activity(desk_id, created_at desc);

create index if not exists idx_desk_activity_actor_user_id
  on public.desk_activity(actor_user_id);

-- Realtime publication
do $$
begin
  begin
    alter publication supabase_realtime add table public.desk_activity;
  exception when duplicate_object then null;
  end;
end $$;

-- RLS
alter table public.desk_activity enable row level security;

drop policy if exists desk_activity_select_accessible on public.desk_activity;
create policy desk_activity_select_accessible on public.desk_activity
for select using (public.user_can_access_desk(desk_id));

drop policy if exists desk_activity_insert_editable on public.desk_activity;
create policy desk_activity_insert_editable on public.desk_activity
for insert with check (
  public.user_can_edit_desk(desk_id)
  and actor_user_id = auth.uid()
);

drop policy if exists desk_activity_update_none on public.desk_activity;
create policy desk_activity_update_none on public.desk_activity
for update using (false) with check (false);

drop policy if exists desk_activity_delete_none on public.desk_activity;
create policy desk_activity_delete_none on public.desk_activity
for delete using (false);

-- ============================================================
-- Done! Your database is now up to date.
-- ============================================================
